### ISSUE TITLE
Render buildings on planets if they exist

### ISSUE THREAD

**Issue by joewledger** [joewledger/gaia#10]
As @remzelg suggested, some simple and minimalistic images would probably do the job. Alternatively, we could use SVG to render them (this would save us having to have a building image for each player color).

**Comment by remzelg** [comment]
SVG would definitely be more performant. However, lets start with images for prototyping. Initial judgement is the performance benefits from using SVG are not worth the extra time cost.

**Comment by joewledger** [comment]
To me, the performance either way is not a huge concern to me.

I was thinking it might actually be easier in terms of implementation if we use SVG, as we won't have to track down (or edit) image files.

**Comment by remzelg** [comment]
Alright sounds good

**Comment by joewledger** [comment]
Donezo in https://github.com/joewledger/gaia/pull/23
