### ISSUE TITLE
First pass of basic UI implementation

### ISSUE THREAD

**Issue by joewledger** [joewledger/gaia#13]
Use wireframe diagrams @remzelg made as a starting point. @remzelg if you could link those here or in the README that would be awesome.

**Comment by remzelg** [comment]
Here is the first iteration of designs.

![mobile menu v1](https://user-images.githubusercontent.com/13786155/49333576-49145d80-f58f-11e8-89ae-205137cf92b9.png)
![player board v1](https://user-images.githubusercontent.com/13786155/49333577-49145d80-f58f-11e8-9918-5b75d3edc8a7.png)
![upgrade menu s v1](https://user-images.githubusercontent.com/13786155/49333578-49acf400-f58f-11e8-9f2f-c7f8f7d7018c.png)
![build menu v1](https://user-images.githubusercontent.com/13786155/49333579-49acf400-f58f-11e8-8482-b9b63bc5f9c4.png)
![desktop layout v2](https://user-images.githubusercontent.com/13786155/49333580-49acf400-f58f-11e8-95f2-ecee58b7ce1f.png)
![distance menu v1](https://user-images.githubusercontent.com/13786155/49333581-49acf400-f58f-11e8-850f-c1115ef5cbbe.png)

**Comment by joewledger** [comment]
Nice job, we should consider moving this to a documentation folder or to the readme.
